export interface Booking {
  id: number
  // Toegang
  access_token?: string
  slug?: string
  portal_title?: string
  contract_info_unlocked?: number
  // Beheer
  feest_datum: string
  type_feest: 'Trouw' | 'Algemeen'
  is_aanvraag: number
  status_contract: number
  status_voorschot: number
  status_vragenlijst: number
  // Contact
  naam_organisator: string
  naam_partner1?: string
  naam_partner2?: string
  bedrijfsnaam?: string
  btw_nr?: string
  email: string
  telefoon: string
  locatie_naam?: string
  locatie_adres?: string
  aantal_gasten?: number
  thema?: string
  publiek_leeftijd?: string
  werk_partner1?: string
  werk_partner2?: string
  hobbys_interesses?: string
  leeftijd_partner1?: number
  leeftijd_partner2?: number
  extra_koppel_info?: string
  anderstalige_gasten?: string
  // Logistiek
  parkeren_info?: string
  gelijkvloers?: number
  backup_contact_naam?: string
  backup_contact_telefoon?: string
  verzoeknummers?: string
  // Planning
  uur_ceremonie?: string
  uur_receptie?: string
  uur_receptie_einde?: string
  uur_receptie2?: string
  uur_receptie2_einde?: string
  uur_diner?: string
  uur_dessert?: string
  uur_dansfeest?: string
  uur_midnightsnack?: string
  einduur?: string
  planning_extra?: string
  // Muziek
  top_genres?: string
  top_genres_extra?: string
  flop_genres?: string
  flop_genres_extra?: string
  must_play?: string
  do_not_play?: string
  spotify_link?: string
  muziek_receptie?: string
  muziek_receptie_extra?: string
  muziek_diner?: string
  muziek_diner_extra?: string
  einde_feest?: string
  intrede_zaal_nummer?: string
  intrede_eretafel_nummer?: string
  intrede_bridesmaids_nummer?: string
  intrede_groomsmen_nummer?: string
  intrede_koppel_nummer?: string
  intrede_anders_nummer?: string
  intrede_taart_nummer?: string
  openingsdans_nummer?: string
  tweede_dans_nummer?: string
  boeket_werpen_nummer?: string
  verjaardag_naam_leeftijd?: string
  // Zaal & Techniek
  zaal_contact?: string
  leveranciers_info?: string
  geluidsbeperking_info?: string
  wifi_code?: string
  speakers_aanwezig?: number
  licht_aanwezig?: number
  micro_aanwezig?: number
  dj_booth_aanwezig?: number
  uplights_aanwezig?: number
  speakers_buiten?: number
  // Extra's
  ceremonie_set?: number
  digital_booth?: number
  retro_booth?: number
  draadloze_speaker?: number
  karaoke?: number
  // Bevestiging
  toestemming_foto?: number
  opmerkingen?: string
  zaal_fotos?: string
  uitnodiging_files?: string
  handtekening_klant?: string
  // Contract & Betaling
  totaalprijs?: number
  basisprijs?: number
  extra_prijzen?: string
  adres_organisator?: string
  voorschot_instructies?: string
  billit_factuur_pdf?: string
  billit_factuur_naam?: string
  contract_pdf?: string
  // Meta
  created_at?: string
  updated_at?: string
  vragenlijst_updated_at?: string
  vragenlijst_first_submitted_at?: string
  aanvraag_reminder_sent_at?: string
  review_sent_at?: string
  feest_herinnering_sent_at?: string
  vragenlijst_diff?: string
  // Klantpagina boolean vlaggen (grote PDFs worden niet meegestuurd)
  has_contract_pdf?: number
  has_billit_factuur_pdf?: number
  // Klant feedback na vragenlijst
  feedback_vragenlijst?: string
  feedback_herkomst?: string
  // Afgewezen aanvragen
  is_afgewezen?: number
  afgewezen_reden?: string
}
